name: flutter_web
publish_to: none

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_web_ui: any
  collection: ^1.0.0
  meta: ^1.1.5
  vector_math: ^2.0.7
  typed_data: ^1.1.6

dev_dependencies:
  flutter_web_test: any
  mockito: ">=3.0.0 <=4.0.0"
  test: ^1.3.0
  path: ^1.6.2
  quiver: ^2.0.1

dependency_overrides:
  flutter_web_test:
    path: ../flutter_web_test
  flutter_web_ui:
    path: ../flutter_web_ui
