name: flutter_go
description: flutter_go

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.0.4

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  event_bus: ^1.0.1
  fluro: ^1.3.4
  image_picker: ^0.4.10
  sqflite: ^0.12.1
  flutter_markdown: ^0.2.0
  url_launcher: ^4.0.1
  fluttertoast: ^2.2.2
  # 本地存储、收藏功能
  shared_preferences: ^0.4.3
  dio: ^1.0.6
  flutter_webview_plugin: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/widgets/elements/Form/Input/TextField/text_field_demo.dart
    - lib/widgets/elements/Form/CheckBox/Checkbox/demo.dart
    - lib/widgets/components/Bar/AppBar/demo.dart
    - lib/widgets/components/Bar/BottomAppBar/demo.dart
    - lib/widgets/components/Bar/ButtonBar/demo.dart
    - lib/widgets/components/Bar/FlexibleSpaceBar/demo.dart
    - lib/widgets/components/Bar/SliverAppBar/demo.dart
    - lib/widgets/components/Bar/SnackBar/demo.dart
    - lib/widgets/components/Bar/SnackBarAction/demo.dart
    - lib/widgets/components/Bar/TabBar/demo.dart
    - lib/widgets/components/Card/Card/demo.dart
    - lib/widgets/components/Chip/Chip/demo.dart
    - lib/widgets/components/Chip/ChipTheme/demo.dart
    - lib/widgets/components/Chip/ChipThemeData/demo.dart
    - lib/widgets/components/Chip/ChoiceChip/demo.dart
    - lib/widgets/components/Chip/FilterChip/demo.dart
    - lib/widgets/components/Chip/inputChip/demo.dart
    - lib/widgets/components/Chip/RawChip/demo.dart
    - lib/widgets/components/Dialog/AboutDialog/demo.dart
    - lib/widgets/components/Dialog/AlertDialog/demo.dart
    - lib/widgets/components/Dialog/Dialog/demo.dart
    - lib/widgets/components/Dialog/SimpleDialog/demo.dart
    - lib/widgets/components/Grid/GridTile/demo.dart
    - lib/widgets/components/Grid/GridTileBar/demo.dart
    - lib/widgets/components/Grid/GridView/demo.dart
    - lib/widgets/components/LIst/AnimatedList/demo.dart
    - lib/widgets/components/LIst/ListBody/demo.dart
    - lib/widgets/components/LIst/ListView/demo.dart
    - lib/widgets/components/Menu/CheckedPopupMenuItem/demo.dart
    - lib/widgets/components/Menu/DropdownMenuItem/demo.dart
    - lib/widgets/components/Menu/PopupMenuButton/demo.dart
    - lib/widgets/components/Menu/PopupMenuDivider/demo.dart
    - lib/widgets/components/Navigation/BottomNavigationBar/demo.dart
    - lib/widgets/components/Navigation/BottomNavigationBarItem/demo.dart
    - lib/widgets/components/Panel/ExpansionPanel/demo.dart
    - lib/widgets/components/Panel/ExpansionPanelList/demo.dart
    - lib/widgets/components/Pick/DayPicker/demo.dart
    - lib/widgets/components/Pick/MonthPicker/demo.dart
    - lib/widgets/components/Pick/ShowdatePicker/demo.dart
    - lib/widgets/components/Pick/YearPicker/demo.dart
    - lib/widgets/components/Progress/CircularProgressIndicator/demo.dart
    - lib/widgets/components/Progress/LinearProgressIndicator/demo.dart
    - lib/widgets/components/Progress/RefreshProgressIndicator/demo.dart
    - lib/widgets/components/Scaffold/Scaffold/demo.dart
    - lib/widgets/components/Scaffold/ScaffoldState/demo.dart
    - lib/widgets/components/Scroll/BoxScrollView/demo.dart
    - lib/widgets/components/Scroll/CustomScrollView/demo.dart
    - lib/widgets/components/Scroll/NestedScrollView/demo.dart
    - lib/widgets/components/Scroll/Scrollable/demo.dart
    - lib/widgets/components/Scroll/ScrollbarPainter/demo.dart
    - lib/widgets/components/Scroll/ScrollMetrics/demo.dart
    - lib/widgets/components/Scroll/ScrollPhysics/demo.dart
    - lib/widgets/components/Scroll/ScrollView/demo.dart
    - lib/widgets/components/Tab/Tab/demo.dart
    - lib/widgets/elements/Form/Button/DropdownButton/demo.dart
    - lib/widgets/elements/Form/Button/FlatButton/demo.dart
    - lib/widgets/elements/Form/Button/FloatingActionButton/demo.dart
    - lib/widgets/elements/Form/Button/IconButton/demo.dart
    - lib/widgets/elements/Form/Button/OutlineButton/demo.dart
    - lib/widgets/elements/Form/Button/PopupMenuButton/demo.dart
    - lib/widgets/elements/Form/Button/RaisedButton/demo.dart
    - lib/widgets/elements/Form/Button/RawMaterialButton/demo.dart
    - lib/widgets/elements/Form/CheckBox/Checkbox/demo.dart
    - lib/widgets/elements/Form/CheckBox/CheckboxListTile/demo.dart
    - lib/widgets/elements/Form/Radio/Radio/demo.dart
    - lib/widgets/elements/Form/Radio/RadioListTile/demo.dart
    - lib/widgets/elements/Form/Slider/Slider/demo.dart
    - lib/widgets/elements/Form/Slider/SliderTheme/demo.dart
    - lib/widgets/elements/Form/Slider/SliderThemeData/demo.dart
    - lib/widgets/elements/Form/Switch/AnimatedSwitcher/demo.dart
    - lib/widgets/elements/Form/Switch/Switch/demo.dart
    - lib/widgets/elements/Form/Switch/SwitchListTile/demo.dart
    - lib/widgets/elements/Frame/Align/Align/demo.dart
    - lib/widgets/elements/Frame/Box/ConstrainedBox/demo.dart
    - lib/widgets/elements/Frame/Box/DecoratedBox/demo.dart
    - lib/widgets/elements/Frame/Box/Fittedbox/demo.dart
    - lib/widgets/elements/Frame/Box/LimitedBox/demo.dart
    - lib/widgets/elements/Frame/Box/OverflowBox/demo.dart
    - lib/widgets/elements/Frame/Box/RenderBox/demo.dart
    - lib/widgets/elements/Frame/Box/RotatedBox/demo.dart
    - lib/widgets/elements/Frame/Box/SizeBox/demo.dart
    - lib/widgets/elements/Frame/Box/SizedOverflowBox/demo.dart
    - lib/widgets/elements/Frame/Box/TextBox/demo.dart
    - lib/widgets/elements/Frame/Box/UnconstrainedBox/demo.dart
    - lib/widgets/elements/Frame/Expanded/Expanded/expanded_demo.dart
    - lib/widgets/elements/Frame/Layout/Center/demo.dart
    - lib/widgets/elements/Frame/Layout/Column/demo.dart
    - lib/widgets/elements/Frame/Layout/Container/demo.dart
    - lib/widgets/elements/Frame/Layout/Row/demo.dart
    - lib/widgets/elements/Frame/Spacing/AnimatedPadding/animatedPadding_demo.dart
    - lib/widgets/elements/Frame/Spacing/Padding/padding_demo.dart
    - lib/widgets/elements/Frame/Spacing/SliverPadding/sliverpadding_demo.dart
    - lib/widgets/elements/Frame/Stack/IndexedStack/demo.dart
    - lib/widgets/elements/Frame/Stack/Stack/demo.dart
    - lib/widgets/elements/Frame/Table/Table/table_demo.dart
    - lib/widgets/elements/Media/Icon/Icon/demo.dart
    - lib/widgets/elements/Media/Icon/IconData/demo.dart
    - lib/widgets/elements/Media/Icon/IconTheme/demo.dart
    - lib/widgets/elements/Media/Icon/IconThemeData/demo.dart
    - lib/widgets/elements/Media/Icon/ImageIcon/demo.dart
    - lib/widgets/elements/Media/Image/AssetImage/assetImage_demo.dart
    - lib/widgets/elements/Media/Image/DecorationImage/decorationImage_demo.dart
    - lib/widgets/elements/Media/Image/DecorationImagePainter/decoration_image_painter_demo.dart
    - lib/widgets/elements/Media/Image/ExactAssetImage/exact_asset_image_demo.dart
    - lib/widgets/elements/Media/Image/FadeInImage/fade_in_image_demo.dart
    - lib/widgets/elements/Media/Image/FileImage/file_image_demo.dart
    - lib/widgets/elements/Media/Image/Image/demo.dart
    - lib/widgets/elements/Media/Image/MemoryImage/memory_image_demo.dart
    - lib/widgets/elements/Media/Image/NetworkImage/network_image_demo.dart
    - lib/widgets/elements/Media/Image/paintImage/paint_image_demo.dart
    - lib/widgets/elements/Media/Image/precacheImage/precache_image_demo.dart
    - lib/widgets/elements/Media/Image/RawImage/raw_image_demo.dart
    - lib/widgets/themes/Material/MaterialApp/demo.dart
    - lib/widgets/themes/Material/MaterialButton/demo.dart
    - lib/widgets/themes/Material/MaterialColor/demo.dart
    - lib/widgets/themes/Material/MaterialPageRoute/demo.dart
    - lib/widgets/themes/Material/MergeableMaterialItem/demo.dart
    - lib/widgets/themes/Cupertino/CupertinoScrollbar/demo.dart
    - lib/widgets/themes/Cupertino/CupertinoSlider/demo.dart
    - lib/widgets/themes/Cupertino/CupertinoSegmentedControl/demo.dart
    - lib/widgets/themes/Cupertino/CupertinoSwitch/demo.dart
    - lib/widgets/themes/Cupertino/CupertinoTabBar/demo.dart
    - lib/widgets/themes/Cupertino/CupertinoTabView/demo.dart
    - assets/app.db
    - assets/images/
    - lib/common/example_code_parser.dart
    - lib/common/syntax_highlighter.dart



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
