name: flutter_web_ui
publish_to: none

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_web: any
  collection: ^1.0.0
  meta: ^1.1.5
  vector_math: ^2.0.7
  intl: any

dev_dependencies:
  path: any
  flutter_web_test: any
  test: ^1.3.0

dependency_overrides:
  flutter_web:
    path: ../flutter_web
  flutter_web_test:
    path: ../flutter_web_test
